# Generated by Django 5.1.6 on 2025-03-16 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_kartonu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hisotria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('typ_operacji', models.CharField(choices=[('Dodaj', 'Dodanie'), ('Usun', 'Usuniecie')], max_length=50)),
                ('ilosc_zmiany', models.IntegerField()),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazyn_app.produkt')),
            ],
        ),
        migrations.CreateModel(
            name='Sekcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('lista_kartonow', models.ManyToManyField(related_name='sekcje', to='magazyn_app.karton')),
            ],
        ),
        migrations.CreateModel(
            name='WariantProduktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rozmiar', models.CharField(max_length=50)),
                ('ilosc', models.IntegerField(default=0)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wariant', to='magazyn_app.produkt')),
            ],
        ),
        migrations.AddField(
            model_name='karton',
            name='produkty',
            field=models.ManyToManyField(related_name='kartony', to='magazyn_app.wariantproduktu'),
        ),
    ]
